### ISSUE TITLE
Crashes when called with -b

### ISSUE THREAD

**Issue by ulrich-teichert-kk** [analogdevicesinc/fru_tools#15]
Hi,

fru-dump crashes when called with -b:
root:~# ./fru-dump -v -b -i /sys/bus/i2c/devices/0-0050/eeprom
read 256 bytes from /sys/bus/i2c/devices/0-0050/eeprom
Date of Man     : Mon Jan  1 00:00:00 1996
Manufacturer    : XXXXXXX
Product Name    : XXXXXXX
Serial Number   :  
Part Number     :  
FRU File ID     :  
Custom Fields:
  Field 0 (len=2): 61 00  |a.|
Segmentation fault

The simple reason is that a NULL-pointer check in free_FRU is missing. I can provide a patch if that's of interest,
CU,
Uli

**Comment by nunojsa** [comment]
Hi,

Thanks for reporting. Yeah. if  you can, please open PR for this (and Sign off your patch).
