### ISSUE TITLE
erroneous bound-checking misses last character in six2ascii

### ISSUE THREAD

**Issue by elodg** [analogdevicesinc/fru_tools#5]
https://github.com/analogdevicesinc/fru_tools/blob/9c360ea67d153fefe32713aa1bfca98d7acd81f9/fru.c#L284-L285

The bound-condition should be i+2<size, because index i+2 is being de-referenced.
This bug causes the last character to be missed if size is multiple of three.

**Comment by rgetz** [comment]
I will have a look, I think this was done to make sure we didn't loose trailing spaces..

Do you have a fru file which doesn't work? Can you attach it for testing?

Thanks

**Comment by elodg** [comment]
Expires in 180 days: https://paste.c-net.org/ParrotAgendas
FMC-specific MultiRecord Subtype 1 [0xb4:0xc2] encodes Device Address MSB 1110 and Device String "TCA9546" in 6-bit ASCII packed format: 0e 3d 86 59 45 59.

**Comment by rgetz** [comment]
Ok - I can replicate. Thanks
```
rgetz@brain:~/github/fru_tools$ ./fru-dump -2 ./fmc_pcam.bin 
read 256 bytes from ./fmc_pcam.bin
Parse Board Area
Parse Board Area done
TCA954	0xe0|0x70 (0b1110nnn[RW]);  
```

when you turn debugging on, it finds things:
```
rgetz@brain:~/github/fru_tools$ ./fru-dump -2 ./fmc_pcam.bin 
read 256 bytes from ./fmc_pcam.bin
Parse Board Area
Parse Board Area done
00: 0e : 00 001110 (0e) 2e '.'
01: 3d : 0011 1101 (34) 54 'T'
02: 86 : 100001 10 (23) 43 'C' | (21) 41 'A'
03: 59 : 01 011001 (19) 39 '9'
04: 45 : 0100 0101 (15) 35 '5'
05: 59 : 010110 01 (14) 34 '4' | (16) 36 '6'
TCA954	0xe0|0x70 (0b1110nnn[RW]);  
rgetz@brain:~/github/fru_tools$ 
```

so you are right - it doesn't print things out.

I fixed it on master.

```
read 256 bytes from ../fru_tools-product/fmc_pcam.bin
TCA9546	0xe0|0x70 (0b1110nnn[RW]);  
```
