### ISSUE TITLE
free_FRU() catches SIGSEGV

### ISSUE THREAD

**Issue by B0P0H0K** [analogdevicesinc/fru_tools#8]
free_FRU() catches SIGSEGV in case fru->MultiRecord_Area == NULL
Command line was "fru-dump -b <file-name>"

Program received signal SIGSEGV, Segmentation fault.
0x0000555555556b22 in free_FRU (fru=0x55555555d890) at fru.c:647
647                     free(fru->MultiRecord_Area->supplies[j]);
(gdb) bt
#0  0x0000555555556b22 in free_FRU (fru=0x55555555d890) at fru.c:647
#1  0x000055555555585a in main (argc=<optimized out>, argv=<optimized out>) at operating-system.c:568
(gdb) p fru
$1 = (struct FRU_DATA *) 0x55555555d890
(gdb) p *fru
$2 = {Internal_Area = 0x0, Chassis_Info = 0x0, Board_Area = 0x55555555d8c0, Product_Info = 0x0, MultiRecord_Area = 0x0}

**Comment by rgetz** [comment]
Can you attach the fru file that you were looking at?

**Comment by B0P0H0K** [comment]
Attaching. Sorry, I needed to cross out the strings that would have identified the manufacturer and the product.
[fru.bin.gz](https://github.com/analogdevicesinc/fru_tools/files/7198605/fru.bin.gz)

**Comment by rgetz** [comment]
master isn't crashing for me.

```
rgetz@brain:~/github/fru_tools$ md5sum ./fru.bin 
7772807566fca289db0ab0bc2845986a  ./fru.bin

rgetz@brain:~/github/fru_tools$ ./fru-dump -b  ./fru.bin 
read 80 bytes from ./fru.bin
fru_dump 0.8.1.9, built 20Sep2021
Board Area Checksum failed
```

if you want to email me the original file, I won't post it anywhere - let me know; it's robin dot getz at analog dot com

**Comment by B0P0H0K** [comment]
Alright then. Close it as "fixed/unknown". I am actually unable to guarantee that this is the exact same image. It's been 5 months since and I don't remember all the details. The code may have drifted too. I blame myself for not attaching the image at the time.
Thank you for your help!

**Comment by rgetz** [comment]
Ok - thanks for following up - I will try to find some other fru tools, and see if I can replicate.
